Feat/filters
Smile-SA/react-front-kit pull request #69
Opened 2023-11-21 12:01 UTC by vapersmile

Add filters component

Add sideMenuFilters component

Modify collapseButtonControlled for add style on collapse component

2023-11-21 14:16 UTC, QuentinLeCaignec commented on packages/react-front-kit/src/Components/CollapseButton/CollapseButtonControlled.tsx
> +  collapseStyle?: Record<string, number | string>;
c'est pas plutôt CSSProperties le type ?

2023-11-21 14:16 UTC, QuentinLeCaignec commented on packages/react-front-kit/src/Components/Filters/Filters.tsx
> +    filterLabelButton = 'Filter',
si c'est un label faut rester cohérent et l'appeler "filterButtonLabel"

2023-11-21 14:16 UTC, QuentinLeCaignec commented on packages/react-front-kit/src/Components/Filters/SidebarFilterMenu/SidebarFilterMenu.tsx
> +    | undefined,
est-ce nécessaire si la prop est déjà optionnelle `?:` ?

2023-11-21 15:37 UTC, tonai commented on .changeset/spicy-moose-juggle.md
> +Add filters componant
typo

2023-11-21 15:37 UTC, tonai commented on packages/react-front-kit/src/Components/CollapseButton/CollapseButtonControlled.tsx
> +          style={collapseStyle}
Plutôt que de faire une props spécifique, profite en pour faire quelque chose de plus générique.
Par exemple en ajoutant plutôt une props `collapseProps` que tu merges ici avec `{...collapseProps}`.
ça permettra de gérer les style mais aussi tout autre propriété que l'on voudrait ajouter.

2023-11-21 15:37 UTC, tonai commented on packages/react-front-kit/src/Components/Filters/Filters.stories.tsx
> +    deleteButtonLabel: 'Supprimer tout',
Anglais

2023-11-21 15:37 UTC, tonai commented on packages/react-front-kit/src/Components/Filters/SidebarFilterMenu/SidebarFilterMenu.mock.tsx
> +      <div style={{ padding: '10px 0 10px 10px' }}>
J'ai l'impression que tu ajoutes ce padding à chaque fois.
Est-ce possible de l'avoir au niveau du composant ? (pour éviter d'avoir besoin de le mettre ici)

2023-11-21 15:37 UTC, tonai commented on packages/react-front-kit/src/Components/Filters/SidebarFilterMenu/SidebarFilterMenu.tsx
> +              }
possible d'utiliser des classes avec le modification en `collapseProps` ?

2023-11-21 15:49 UTC, tonai commented on packages/react-front-kit/src/Components/Filters/SidebarFilterMenu/SidebarFilterMenu.tsx
> +        // prettier-ignore
Pour éviter le commentaire essaye de calculer la valeur dans une variable en dehors du JSX et ensuite tu utilises la variables dans le JSX: `collapseProps={collapseProps}`

2023-11-22 09:30 UTC, vapersmile commented on .changeset/spicy-moose-juggle.md
> +Add filters componant
Je ne comprend pas ton commentaire ?

2023-11-22 09:37 UTC, vapersmile commented on packages/react-front-kit/src/Components/Filters/SidebarFilterMenu/SidebarFilterMenu.tsx
> +        // prettier-ignore
J'ai encore ce problème

2023-11-22 09:37 UTC, tonai commented on .changeset/spicy-moose-juggle.md
> +Add filters componant
Typo ça veut dire qu'il y a une faute.
=> componEnt

2023-11-22 09:50 UTC, vapersmile commented on packages/react-front-kit/src/Components/CollapseButton/CollapseButtonControlled.tsx
> +          style={collapseStyle}
Il y a déjà un élément reste dans les props de mon composant, j'ai une erreur TS qui me dit `Un élément rest doit être le dernier dans un modèle de déstructuration` quand j'en mes deux comme là : 
` const {
    collapseStyle,
    children,
    component: Component = 'button',
    componentProps,
    fullWidth = true,
    id,
    isOpenOnSelect = false,
    label,
    leftIcon,
    level = 0,
    line,
    onCollapseChange,
    onSelect,
    opened = false,
    radius = 0,
    size = 'md',
    selected,
    ...buttonProps,
    ...collapseProps,
  } = props;
`

2023-11-22 10:33 UTC, vapersmile commented on packages/react-front-kit/src/Components/Filters/SidebarFilterMenu/SidebarFilterMenu.tsx
> +              }
Dans le className du composant enfant, il y a déjà une classe dans le class Name, j'ai utilisé le propos style pour ne pas écraser cette classe conditionnelle.

2023-11-22 12:35 UTC, vapersmile commented on .changeset/spicy-moose-juggle.md
> +Add filters componant
Ah autant pour moi

2023-11-22 15:26 UTC, tonai commented on packages/react-front-kit/src/Components/CollapseButton/CollapseButtonControlled.tsx
> +          style={collapseStyle}
Je parle d'une props à part entière, pas de destructuration.
`const {autresProps, selected, collapseProps, ...buttonProps} = props;`

2023-11-22 15:27 UTC, tonai commented on packages/react-front-kit/src/Components/Filters/SidebarFilterMenu/SidebarFilterMenu.tsx
> +        // prettier-ignore
C'est quoi le problème avec prettier ?

2023-11-22 17:05 UTC, tonai requested changes

2023-11-22 17:05 UTC, tonai commented on packages/react-front-kit/src/Components/CollapseButton/CollapseButtonControlled.tsx
> +  collapseProps?: Omit<CollapseProps, 'in'>;
Je pense que le bon typage serait plutôt:
```suggestion
  collapseProps?: Partial<CollapseProps>;
```

2023-11-22 17:05 UTC, tonai commented on packages/react-front-kit/src/Components/Filters/SidebarFilterMenu/SidebarFilterMenu.tsx
> +        collapseProps={{ children: undefined, style: collapseStyle }}
Avec la modification de typage je pense que ce n'est pas nécessaire de passer la props children

2023-11-23 08:17 UTC, vapersmile commented on packages/react-front-kit/src/Components/Filters/SidebarFilterMenu/SidebarFilterMenu.tsx
> +        collapseProps={{ children: undefined, style: collapseStyle }}
J'ai une erreur si je ne met pas le children

2023-11-23 08:52 UTC, tonai approved these changes

2023-11-23 08:54 UTC, merged